---
- hosts: 127.0.0.1
  user: ubuntu
  tasks:
    - name: "apt-get install git"
      apt: pkg=git
      sudo: yes
    - name: "apt-get install emacs"
      apt: pkg=emacs
      sudo: yes
    - name: "apt-get install yaml-mode"
      apt: pkg=yaml-mode
      sudo: yes
    - name: "apt-get install tmux"
      apt: pkg=tmux
      sudo: yes
    - name: "apt-get install  build-essential"
      action: apt pkg=build-essential
      sudo: yes
    - name: "apt-get install mongodb"
      apt: pkg=mongodb-server
      sudo: yes
    - name: "apt-get install python-mongodb"
      apt: pkg=python-pymongo
      sudo: yes
    - name: "apt-get install python-pip"
      apt: pkg=python-pip
      sudo: yes
    - name: "apt-get install python-dev"
      apt: pkg=python-dev
      sudo: yes
    - name: "apt-get install sysstat"
      apt: pkg=sysstat
      sudo: yes
    - name: "apt-get install ntp"
      apt: pkg=ntp
      sudo: yes
    - name: "apt-get install python-oauth2client"
      apt: pkg=python-oauth2client
      sudo: yes
    - name: "apt-get install python-httplib2"
      apt: pkg=python-httplib2
      sudo: yes
    - name: "Install google api clinet"
      action: apt pkg={{item}} state=present
      with_items:
        - python-pygooglechart
        - python-google-apputils
        - python-googleapi
        - python-googleapi-samples
      sudo: yes
    - name: "Install python-flask"
      action: apt pkg={{item}} state=present
      with_items:
        - python-flask
        - python-flaskext.wtf
        - python-flask-doc
      sudo: yes
    - pip: name=mongokit
      sudo: yes
    - pip: name=Flask-MongoKit
      sudo: yes
