---
- hosts: 127.0.0.1
  user: ubuntu
  tasks:
    - name: "apt-get install git"
      apt: pkg=git
      sudo: yes
    - name: "apt-get install emacs"
      apt: pkg=emacs
      sudo: yes
    - name: "apt-get install yaml-mode"
      apt: pkg=yaml-mode
      sudo: yes
    - name: "apt-get install tmux"
      apt: pkg=tmux
      sudo: yes
    - name: "apt-get install  build-essential"
      action: apt pkg=build-essential
      sudo: yes
    - name: "apt-get install mongodb"
      apt: pkg=mongodb-server
      sudo: yes
    - name: "apt-get install mongo-client"
      apt: pkg=mongo-client
      sudo: yes
    - name: "apt-get install python-mongodb"
      apt: pkg=python-pymongo
      sudo: yes
    - name: "apt-get install python-pip"
      apt: pkg=python-pip
      sudo: yes
    - name: "apt-get install python-dev"
      apt: pkg=python-dev
      sudo: yes
    - name: "apt-get install sysstat"
      apt: pkg=sysstat
      sudo: yes
